version: "3.8"

services:
  db:
    image: postgres:18
    container_name: novacart_db
    restart: always
    environment:
      POSTGRES_USER: novacart
      POSTGRES_PASSWORD: novacart123
      POSTGRES_DB: novacart
    ports:
      - "5432:5432"